---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: pg-client-ca
spec:
  isCA: true
  commonName: pg-client-ca
  secretName: pg-client-ca
  privateKey:
    algorithm: ECDSA
    size: 256
  issuerRef:
    name: selfsigned-cluster-issuer
    kind: ClusterIssuer
    group: cert-manager.io
---
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: pg-client-issuer
spec:
  ca:
    secretName: pg-client-ca
---
apiVersion: v1
kind: Secret
metadata:
  name: pg-replication-cert
  labels:
    cnpg.io/reload: ""
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: pg-replication
spec:
  secretName: pg-replication-cert
  usages:
    - client auth
  commonName: replication
  issuerRef:
    name: client-issuer
    kind: ClusterIssuer
    group: cert-manager.io
