---
# yaml-language-server: $schema=https://datreeio.github.io/CRDs-catalog/postgresql.cnpg.io/cluster_v1.json
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: postgres
spec:
  imageName: ghcr.io/cloudnative-pg/postgresql:17.7
  instances: 3
  certificates:
    serverCASecret: pg-server-cert
    serverTLSSecret: pg-server-cert
    clientCASecret: pg-replication-cert
    replicationTLSSecret: pg-replication-cert
  primaryUpdateStrategy: unsupervised
  storage:
    size: 50Gi
    storageClass: openebs-hostpath
  enableSuperuserAccess: true
  postgresql:
    pg_hba:
      - hostssl teleport all 0.0.0.0/0 cert
      - hostssl teleport_events all 0.0.0.0/0 cert
    parameters:
      max_connections: "400"
  resources:
    requests:
      cpu: '1'
      memory: 4Gi
    limits:
      memory: 4Gi
  monitoring:
    enablePodMonitor: true
