apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: teleport-cluster
  namespace: argocd
spec:
  sources:
  - repoURL: https://charts.releases.teleport.dev
    chart: teleport-cluster
    targetRevision: 18.5.1
    helm:
      valueFiles:
      - $values/argocd/apps/development/teleport-cluster/values.yaml
  - repoURL: 'https://github.com/rcanderson23/homelab2.git'
    targetRevision: main
    ref: values
  - repoURL: 'https://github.com/rcanderson23/homelab2.git'
    path: 'argocd/apps/development/teleport-cluster/manifests'
    targetRevision: main
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - ServerSideApply=true
  destination:
    server: https://kubernetes.default.svc
    namespace: teleport-cluster
