monitoring:
  podMonitorEnabled: true
  podMonitorAdditionalLabels:
    release: kps 

  grafanaDashboard:
    create: false
    # -- Allows overriding the namespace where the ConfigMap will be created, defaulting to the same one as the Release.
    namespace: ""
    # -- The name of the ConfigMap containing the dashboard.
    configMapName: "cnpg-grafana-dashboard"
    # -- Label that ConfigMaps should have to be loaded as dashboards.  DEPRECATED: Use labels instead.
    sidecarLabel: "grafana_dashboard"
    # -- Label value that ConfigMaps should have to be loaded as dashboards.  DEPRECATED: Use labels instead.
    sidecarLabelValue: "1"
    # -- Labels that ConfigMaps should have to get configured in Grafana.
    labels: {}
    # -- Annotations that ConfigMaps can have to get configured in Grafana.
    annotations: {}
