---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: pushover-credentials
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-secretsmanager
  target:
    name: pushover-credentials
    template:
      data:
        PUSHOVER_TOKEN: |-
          {{ .token }}
        PUSHOVER_USER_KEY: |-
          {{ .user_key }}
  data:
  - remoteRef:
      key: 4eebfacf-4915-4afe-8d5d-b3b6017a9e70
    secretKey: token
  - remoteRef:
      key: 7a9e326f-3c7a-47ca-8d40-b26b014a7240
    secretKey: user_key
