---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: pg-client
spec:
  commonName: teleport
  secretName: pg-client
  privateKey:
    algorithm: ECDSA
    size: 256
  issuerRef:
    name: pg-client-issuer
    kind: ClusterIssuer
    group: cert-manager.io
