---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: teleport-license
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-secretsmanager
  target:
    name: teleport-license
    template:
      data:
        license.pem: |-
          {{ .license }}
  data:
  - remoteRef:
      key: c82794f8-bf53-4d83-91a6-b3bb0174eb9b
    secretKey: license

